### ISSUE TITLE
/tutorial.html#/21 linked stylesheets dont work

### ISSUE THREAD

**Issue by elliotthilaire** [railsgirls-bne/railsgirls-bne.github.io#28]
> At the moment, the app doesn't look nice. Lets go on and add some CSS to pretty it up. On the left panel of the editor in c9.io, open the file app/views/layouts/application.html.erb. This is your default layout file.
Look for this line <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %> Add these lines of code above this line.
                <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css">
                <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css">
            

Adding style sheet tags do not have an affect. (Already mentioned by langs).

Caused by:
Timestamp: 21/07/2015 7:41:15 PM
Error: railsgirls.com:443 uses an invalid security certificate.

You cannot just use http://railsgirls.com/assets/bootstrap.css since cloud9 serves the app over https and browsers block 'mixed' content.

**Comment by SorchaAbel** [comment]
Ah nice one @ElliottHilaire

On 24 July 2015 at 08:45, Elliott Hilaire <notifications@github.com> wrote:

> Closed #28
> <https://github.com/railsgirls-bne/railsgirls-bne.github.io/issues/28>
> via #45
> <https://github.com/railsgirls-bne/railsgirls-bne.github.io/pull/45>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/railsgirls-bne/railsgirls-bne.github.io/issues/28#event-363919611>
> .
>



-- 
Sorcha Abel
IT Software Developer

 T 07 3319 4430
E sorcha.abel@htw.com.au

Level 1, 811 Gympie Road, Chermside, QLD, 4032
PO Box 61, Chermside South, QLD, 4032

HERRON TODD WHITE | www.htw.com.au

-- 
Please consider the impact on the environment before you print this email

The information contained in this e-mail and any attachments are strictly 
private and confidential. This e-mail should only be read by the intended 
addressee. If you are not the intended addressee, you are strictly 
prohibited from using, reproducing, disclosing, or distributing the 
information contained herein and any attached files and/or documents. 
Unless stated otherwise, this email represents only the views of the sender 
and not the views of Herron Todd White. Before opening or using any files 
and/or attachments, we recommend you run your own virus protection, as 
although we will not knowingly transmit a virus, Herron Todd White accepts 
no liability for virus transmission. Liability limited by a scheme approved 
under Professional Standards Legislation. The scheme does not apply within 
Tasmania.
